In [9]:
#6.1

#参考模型：https://www.doc88.com/p-7844984057765.html
#x[j]0或1表示是否对该项目进行投资
import cvxpy as cp
import numpy as np
c = np.array([-150,-210,-60,-80,-180]) #定义目标向量
a = np.array([[210,300,100,130,260],[1,1,1,0,0],[0,0,0,1,1],[-1,0,0,0,1]])#定义约束矩阵
b = np.array([600,1,1,0])#定义右边约束矩阵
x = cp.Variable(5,integer=True)#定义五个整型变量
obj = cp.Minimize(c*x)#构造目标函数
cons =[a*x <= b,x>=0,x<=1]#构造约束条件
prob = cp.Problem(obj,cons)#构造问题模型
prob.solve(solver = 'GLPK_MI',verbose = True)#求解问题
print('收益最优值为：',-prob.value)
print('投资最优解为',x.value)

                                     CVXPY                                     
                                     v1.2.0                                    
(CVXPY) May 22 12:36:31 PM: Your problem has 5 variables, 3 constraints, and 0 parameters.
(CVXPY) May 22 12:36:31 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 22 12:36:31 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 22 12:36:31 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) May 22 12:36:31 PM: Compiling problem (target solver=GLPK_MI).
(CVXPY) May 22 12:36:31 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing 

C:\Users\goodboy\AppData\Local\Programs\Python\Python39\lib\site-packages\cvxpy\expressions\expression.py:593: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 15 times so far.

  warnings.warn(msg, UserWarning)
C:\Users\goodboy\AppData\Local\Programs\Python\Python39\lib\site-packages\cvxpy\expressions\expression.py:593: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 16 times

In [10]:
#6.2

#目标函数：收入max，约束：重量限制
import cvxpy as cp
import numpy as np
c = np.array([-3,-5,-2,-4,-2,-3]) #定义目标向量
a = np.array([8,13,6,9,5,7])#定义约束矩阵
b = np.array([24])#定义右边约束矩阵
x = cp.Variable(6,integer=True)#定义六个整型变量
obj = cp.Minimize(c*x)#构造目标函数
cons =[a*x <= b,x>=0,x<=1]#构造约束条件
prob = cp.Problem(obj,cons)#构造问题模型
prob.solve(solver = 'GLPK_MI',verbose = True)#求解问题
print('总收入最优值为：',-prob.value)
print('选运最优解为',x.value)

                                     CVXPY                                     
                                     v1.2.0                                    
(CVXPY) May 22 12:39:59 PM: Your problem has 6 variables, 3 constraints, and 0 parameters.
(CVXPY) May 22 12:39:59 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 22 12:39:59 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 22 12:39:59 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) May 22 12:39:59 PM: Compiling problem (target solver=GLPK_MI).
(CVXPY) May 22 12:39:59 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing 

C:\Users\goodboy\AppData\Local\Programs\Python\Python39\lib\site-packages\cvxpy\expressions\expression.py:593: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 17 times so far.

  warnings.warn(msg, UserWarning)
C:\Users\goodboy\AppData\Local\Programs\Python\Python39\lib\site-packages\cvxpy\expressions\expression.py:593: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 18 times

In [ ]:
#6.3

#https://blog.csdn.net/qq_29831163/article/details/89387723?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165326505116782395338282%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=165326505116782395338282&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-89387723-null-null.142^v10^pc_search_result_control_group,157^v4^control&utm_term=%E9%9D%A2%E8%AF%95%E9%A1%BA%E5%BA%8F%E9%97%AE%E9%A2%98&spm=1018.2226.3001.4187
#python没有实现，不太会解这类模型，找到csdn上的lingo求解模型
'''
安排4名同学的面试顺序，使完成全部面试花费的时间最少
t[i][j]表示第i名同学参加第j阶段面试所需要的时间,x[i][j]表示第i个同学参加第j阶段面试的开始时间
目标函数即是完成全部面试所花费的最少时间minT={maxi(x[i][3],+t[i][3])}
'''

In [49]:
#6.4
'''
先总结：这个问题中，约束都很清晰，但是默认cvxpy.solve求解器无法求解
可以更换求解器进行求解（若未安装，需要安装）：
# Solve with ECOS
# Solve with ECOS_BB
# Solve with CVXOPT
# Solve with SCS
# Solve with GLPK
# Solve with GLPK_MI
# Solve with GUROBI
# Solve with MOSEK
# Solve with Elemental
# Solve with CBC
'''
'''
每个季度生产能力 <= 100
第一季度：x1>=40
第二季度：(x1-40)+x2>=60
第三季度：(x1-40)+x2-60+x3 = 80
目标函数：min z = 50x1+0.2x2**2+4(x1-40)+50x2+0.2x2**2+4(x1+x2-100)+50x3+0.2x3**2
'''
import numpy as np
import cvxpy as cp
c1= np.array([0.2,0.2,0.2])
c2 = np.array([58,54,50])
a = np.array([[-1,0,0],[-1,-1,0],[1,0,0],[0,1,0],[0,0,1],[0,-1,0],[0,0,-1]])
b = np.array([-40,-100,100,100,100,0,0])
x = cp.Variable(3, integer=True)
obj = cp.Minimize(c1*x**2+c2*x-560)
Aeq = np.array([1,1,1])
Beq = np.array([180])
con =[a*x <= b, Aeq*x == Beq]
prob = cp.Problem(obj,con)
prob.solve(solver=cp.ECOS_BB)
print('最优解为',x.value)
print('最优值为',prob.value)

最优解为 [50. 60. 70.]
最优值为 11279.999999974612


C:\Users\goodboy\AppData\Local\Programs\Python\Python39\lib\site-packages\cvxpy\expressions\expression.py:593: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 122 times so far.

  warnings.warn(msg, UserWarning)
C:\Users\goodboy\AppData\Local\Programs\Python\Python39\lib\site-packages\cvxpy\expressions\expression.py:593: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 123 tim

In [53]:
#6.5
#二次函数的极值问题，即求二次型矩阵的特征值即可
#A = [[1,4,5],[4,2,6],[5,6,3]],x1^2+x2^2+x3^2=1
import numpy as np
P = np.array([[1,4,5],[4,2,6],[5,6,3]])
eigenvalues, eigenvectors = np.linalg.eig(P)#求特征值和特征向量
print("eigenvalues: ", eigenvalues)
print("eigenvectors: ", eigenvectors)
#所以最大值为12.17

eigenvalues:  [12.17597107 -2.50728797 -3.6686831 ]
eigenvectors:  [[ 0.49659978  0.80958546 -0.31298568]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.64811675 -0.10600965  0.7541264 ]]


In [138]:
#6.6

#即max服务人数 and max服务满意度
'''
x[i][j] = 0或者1  表示指派第i（i = 1,2,3）人，去完成第j（j = 1,2,3）项任务
x[i][1]+x[i][2]+x[i][3] = 1
x[i][1]+x[i][2]+x[i][3] = 1
目标函数： max c[i][j]*x[i][j]*d[i][j]
'''
#可以利用人数*满意度决定 决定最终的安排
# Solve with ECOS
# Solve with ECOS_BB
# Solve with CVXOPT
# Solve with SCS
# Solve with GLPK
# Solve with GLPK_MI
# Solve with GUROBI
# Solve with MOSEK
# Solve with Elemental
# Solve with CBC
import cvxpy as cp
import numpy as np
c = np.array( [[120,96,100],
              [72,75,81],
              [54,50,80]])
x = cp.Variable((3,3),integer = True)
obj = cp.Minimize(cp.sum(cp.multiply(-c,x)))
con = [0 <= x, x <= 1, cp.sum(x, axis = 0, keepdims = True) == 1,
                       cp.sum(x, axis = 1, keepdims = True) == 1]
prob = cp.Problem(obj, con)
prob.solve(solver = 'GLPK_MI')
print("最优值为:", -prob.value)
print("最优解为：", x.value)
#所以最终安排第一个在第一个位置，第二个人在第二个位置，第三个人在第三个位置


最优值为: 275.0
最优解为： [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
