In [14]:
#9.1

import numpy as np
a = np.array([[8.1,255,12.6,13.2,76,5.4],
              [6.7,210,13.2,10.7,102,7.2],
              [6.0,233,15.3,9.5,63,3.1],
              [4.5,202,15.2,13,120,2.6]])
for j in range(0,6):#数据归一化处理
    a[:,j] = (a[:,j]-min(a[:,j]))/(max(a[:,j])-min(a[:,j]))
print(a)#查看数据的表现情况
#topsis方法
cplus = a.max(axis = 0)
cminus = a.min(axis = 0)
print('正理想解=',cplus,'负理想解=',cminus)
print(a-cplus)#每一列都减去cplus
d1 = np.linalg.norm(a-cplus,axis = 1)
d2 = np.linalg.norm(a-cminus,axis = 1)
print(d1,d2)#显示到正理想解和负理想解的距离
f1 = d2/(d1+d2)
print('topsis的评价值为：',f1)#最终经过综合评估，1号方案可能比较适合
#灰色关联分析
t = cplus-a#计算参考序列与每个序列的差
print('\n',t)
mmin = t.min()#计算最小值
print(mmin)
mmax = t.max()#计算最大值
print(mmax)
rho = 0.5 #分辨系数
xs = (mmin + rho*mmax)/(t+rho*mmax)#计算灰色关联系数
f2 = xs.mean(axis = 1)#求每一行的均值
print("关联系数=",xs,"\n关联度=",f2)#显示灰色关联系数与灰色关联度，可以看出依旧是方案1较为合适

[[1.         1.         0.         1.         0.22807018 0.60869565]
 [0.61111111 0.1509434  0.22222222 0.32432432 0.68421053 1.        ]
 [0.41666667 0.58490566 1.         0.         0.         0.10869565]
 [0.         0.         0.96296296 0.94594595 1.         0.        ]]
正理想解= [1. 1. 1. 1. 1. 1.] 负理想解= [0. 0. 0. 0. 0. 0.]
[[ 0.          0.         -1.          0.         -0.77192982 -0.39130435]
 [-0.38888889 -0.8490566  -0.77777778 -0.67567568 -0.31578947  0.        ]
 [-0.58333333 -0.41509434  0.         -1.         -1.         -0.89130435]
 [-1.         -1.         -0.03703704 -0.05405405  0.         -1.        ]]
[1.32249565 1.42594901 1.81851712 1.73328982] [1.85000714 1.42089892 1.23593709 1.67991411]
topsis的评价值为： [0.58313806 0.49911304 0.40463435 0.492181  ]

 [[0.         0.         1.         0.         0.77192982 0.39130435]
 [0.38888889 0.8490566  0.77777778 0.67567568 0.31578947 0.        ]
 [0.58333333 0.41509434 0.         1.         1.         0.89130435]
 [1.      

In [61]:
#9.2

''''
经过分析，按照多数比例，第9家公司的经济效益较好，第8家企业的经济效益较差
'''
import numpy as np
b = np.array([[1.611,10.59,0.69,1.67],
             [1.429,9.44,0.61,1.50],
             [1.447,5.97,0.24,1.25],
             [1.572,10.78,0.75,1.71],
             [1.483,10.99,0.75,1.44],
             [1.371,6.46,0.41,1.31],
             [1.665,10.51,0.53,1.52],
             [1.403,6.11,0.17,1.32],
             [2.62,21.51,1.40,2.59],
             [2.033,24.15,1.80,1.89],
             [2.015,26.86,1.93,2.02],
             [1.501,9.74,0.87,1.48],
             [1.578,14.52,1.12,1.47],
             [1.735,14.64,1.21,1.91],
             [1.453,12.88,0.87,1.52],
             [1.765,17.94,0.89,1.40],
             [1.532,29.42,2.52,1.80],
             [1.488,9.23,0.81,1.45],
             [2.586,16.07,0.82,1.83],
             [1.992,2.63,1.01,1.89]])
print(b.shape)
#topsis方法
for j in range(0,4):#数据归一化处理
    b[:,j] = (b[:,j]-min(b[:,j]))/(max(b[:,j])-min(b[:,j]))
print(b)#查看数据的表现情况
print('\n')
print('*'*30)
print('TOPSIS分析')
cplus2 = b.max(axis = 0)
cminus2 = b.min(axis = 0)
print('正理想解为：',cplus2,'负理想解为：',cminus2)
d3 = np.linalg.norm(b-cplus2,axis = 1)
d4 = np.linalg.norm(b-cminus2,axis = 1)
print(d3,d4)#显示到正理想解和负理想解的距离
f2 = d4/(d3+d4)
print('topsis的评价值为：',f2)#
print('企业效益最好的是第{}家企业'.format(f2.argmax()+1))
print('企业效益最差的是第{}家企业'.format(f2.argmin()+1))
print('\n')
print('*'*30)
print('灰色关联分析')
t = cplus2-b#计算参考序列与每个序列的差
mmin = t.min()#计算最小值
mmax = t.max()#计算最大值
rho = 0.5 #分辨系数
xs = (mmin + rho*mmax)/(t+rho*mmax)#计算灰色关联系数
f3 = xs.mean(axis = 1)#求每一行的均值
print("关联系数=",xs,"\n关联度=",f3)#显示灰色关联系数与灰色关联度，可以看出依旧是方案1较为合适
print('企业效益最好的是第{}家企业'.format(f3.argmax()+1))
print('企业效益最差的是第{}家企业'.format(f3.argmin()+1))
print('\n')
print('*'*30)
print('熵值法')
b1 = np.array([[1.611,10.59,0.69,1.67],
             [1.429,9.44,0.61,1.50],
             [1.447,5.97,0.24,1.25],
             [1.572,10.78,0.75,1.71],
             [1.483,10.99,0.75,1.44],
             [1.371,6.46,0.41,1.31],
             [1.665,10.51,0.53,1.52],
             [1.403,6.11,0.17,1.32],
             [2.62,21.51,1.40,2.59],
             [2.033,24.15,1.80,1.89],
             [2.015,26.86,1.93,2.02],
             [1.501,9.74,0.87,1.48],
             [1.578,14.52,1.12,1.47],
             [1.735,14.64,1.21,1.91],
             [1.453,12.88,0.87,1.52],
             [1.765,17.94,0.89,1.40],
             [1.532,29.42,2.52,1.80],
             [1.488,9.23,0.81,1.45],
             [2.586,16.07,0.82,1.83],
             [1.992,2.63,1.01,1.89]])
n = b1.shape[0]
s = b1.sum(axis = 0)#逐列求和
P = (1/s)*b1#求特征比重矩阵
e = -(P*np.log(P)).sum(axis=0)/np.log(n) #计算熵值
g = 1-e#计算差异系数
w = g/sum(g)#计算权重
F = P @ w
print("P={}\ne={}\ng = {}\nw={}\nF = {}".format(P,e,g,w,F))
print('企业效益最好的是第{}家企业'.format(F.argmax()+1))
print('企业效益最差的是第{}家企业'.format(F.argmin()+1))

(20, 4)
[[0.19215372 0.29712579 0.2212766  0.31343284]
 [0.04643715 0.25419933 0.18723404 0.18656716]
 [0.06084868 0.12467339 0.02978723 0.        ]
 [0.16092874 0.30421799 0.24680851 0.34328358]
 [0.08967174 0.31205674 0.24680851 0.14179104]
 [0.         0.14296379 0.10212766 0.04477612]
 [0.23538831 0.2941396  0.15319149 0.20149254]
 [0.0256205  0.12989922 0.         0.05223881]
 [1.         0.70474057 0.52340426 1.        ]
 [0.53002402 0.80328481 0.69361702 0.47761194]
 [0.51561249 0.90444196 0.74893617 0.57462687]
 [0.10408327 0.26539754 0.29787234 0.17164179]
 [0.16573259 0.44382232 0.40425532 0.1641791 ]
 [0.29143315 0.44830161 0.44255319 0.49253731]
 [0.06565252 0.38260545 0.29787234 0.20149254]
 [0.31545236 0.5714819  0.30638298 0.1119403 ]
 [0.12890312 1.         1.         0.41044776]
 [0.09367494 0.24636058 0.27234043 0.14925373]
 [0.97277822 0.50167973 0.27659574 0.43283582]
 [0.49719776 0.         0.35744681 0.47761194]]


******************************
TOPSIS分析
正理想解为： [1